In [56]:
"""
Author(s): Steven van den Broek, Yuqin Cui
Created: 2019-05-08
Edited: 2019-05-08
"""

'\nAuthor(s): Steven van den Broek, Yuqin Cui\nCreated: 2019-05-08\nEdited: 2019-05-08\n'

In [42]:
import numpy as np
import pandas as pd
import panel as pn
import param
import hvplot.pandas
from colorcet import palette

In [43]:
fname = 'GephiMatrix_author_similarity.csv'
f = open(fname, 'r')

# Get author names
line1 = f.readline()
names = line1[1:].split(';');

seen = {}
dupes = []

for index, name in enumerate(names):
    if name not in seen:
        seen[name] = 1
    else:
        if seen[name] == 1:
            dupes.append((index, name))
        seen[name] += 1

# add 1, 2 etc after the name
for pair in dupes:
    index = pair[0]
    name = pair[1]
    for i in range(seen[name]):
        names[index] = name + str((i+1))
        #print(names[index])

# Read csv
df = pd.read_csv(f, names=names, sep=';')

# Fix it
df = df.reset_index(level=1)
names.append("delete")
names = [name.replace('_', ' ') for name in names]
df.columns = names
del df["delete"]
df.set_index([df.columns], inplace=True)

# Get names again for later use
names = df.columns.tolist()

# Get 150*150 sub matrix since otherwise the plot is very slow..
df = df.head(150)[names[0:150]]
names = df.columns.tolist()
df.head()

Jim Thomas  Eleftherios Koutsofios  Lawrence A. Rowe  \
Jim Thomas                1.000000                0.097384          0.125630   
Eleftherios Koutsofios    0.097384                1.000000          0.223607   
Lawrence A. Rowe          0.125630                0.223607          1.000000   
Jonathan I. Helfman       0.109691                0.144620          0.242536   
Mary Brewster             0.275405                0.281718          0.094491   

                        Jonathan I. Helfman  Mary Brewster  Min Chen  \
Jim Thomas                         0.109691       0.275405  0.195006   
Eleftherios Koutsofios             0.144620       0.281718  0.235008   
Lawrence A. Rowe                   0.242536       0.094491  0.181902   
Jonathan I. Helfman                1.000000       0.229175  0.294118   
Mary Brewster                      0.229175       1.000000  0.297927   

                        Christopher G. Healey  Mac Holden   M. Gray  \
Jim Thomas                           0.196239    0.317986  0.407599   
Eleftherios Koutsofios               0.383180    0.365148  0.132508   
Lawrence A. Rowe                     0.123579    0.255155  0.027778   
Jonathan I. Helfman                  0.173840    0.049507  0.053897   
Mary Brewster                        0.336302    0.115728  0.356966   

                        Jason Stewart  ...  Daniel Keim  Kenneth Utting  \
Jim Thomas                        0.0  ...     0.098332        0.311889   
Eleftherios Koutsofios            0.0  ...     0.115145        0.172133   
Lawrence A. Rowe                  0.0  ...     0.080920        0.072169   
Jonathan I. Helfman               0.0  ...     0.064230        0.525105   
Mary Brewster                     0.0  ...     0.175167        0.245495   

                        Ted Selker  Gabor T. Herman  Laxmi Parida  \
Jim Thomas                0.179382         0.235521      0.185396   
Eleftherios Koutsofios    0.201843         0.426963      0.172848   
Lawrence A. Rowe          0.246183         0.292925      0.052705   
Jonathan I. Helfman       0.417957         0.284179      0.076696   
Mary Brewster             0.255883         0.319844      0.099602   

                        Jeannine Pinto  Jonathan Furner  Clayton Lewis  \
Jim Thomas                    0.134840         0.147984       0.279826   
Eleftherios Koutsofios        0.000000         0.400819       0.434813   
Lawrence A. Rowe              0.000000         0.128037       0.220971   
Jonathan I. Helfman           0.000000         0.341589       0.064312   
Mary Brewster                 0.253546         0.338754       0.150334   

                        Francis P. Boscoe  Ian M. Soboroff  
Jim Thomas                       0.262875         0.058026  
Eleftherios Koutsofios           0.225279         0.258199  
Lawrence A. Rowe                 0.087186         0.072169  
Jonathan I. Helfman              0.225554         0.350070  
Mary Brewster                    0.483312         0.163663  

[5 rows x 150 columns]

In [44]:
#solid = df.reset_index()
#liquid = solid.melt(id_vars='index', value_vars=list(df.columns[1:]), value_name="Similarity", var_name="name2")
#liquid.columns = ['name1', 'name2', 'similarity']
#liquid.head()

In [45]:
#liquid.hvplot.heatmap('name1', 'name2', 'similarity',
#                      height=500, width=600, flip_yaxis=True, xaxis=None, yaxis=None)

In [46]:
#convert similarity into unsimilarity (1.0 - similarity)
for name in names:
    df[name] = 1 - df[name]
df.head()

Jim Thomas  Eleftherios Koutsofios  Lawrence A. Rowe  \
Jim Thomas                0.000000                0.902616          0.874370   
Eleftherios Koutsofios    0.902616                0.000000          0.776393   
Lawrence A. Rowe          0.874370                0.776393          0.000000   
Jonathan I. Helfman       0.890309                0.855380          0.757464   
Mary Brewster             0.724595                0.718282          0.905509   

                        Jonathan I. Helfman  Mary Brewster  Min Chen  \
Jim Thomas                         0.890309       0.724595  0.804994   
Eleftherios Koutsofios             0.855380       0.718282  0.764992   
Lawrence A. Rowe                   0.757464       0.905509  0.818098   
Jonathan I. Helfman                0.000000       0.770825  0.705882   
Mary Brewster                      0.770825       0.000000  0.702073   

                        Christopher G. Healey  Mac Holden   M. Gray  \
Jim Thomas                           0.803761    0.682014  0.592401   
Eleftherios Koutsofios               0.616820    0.634852  0.867492   
Lawrence A. Rowe                     0.876421    0.744845  0.972222   
Jonathan I. Helfman                  0.826160    0.950493  0.946103   
Mary Brewster                        0.663698    0.884272  0.643034   

                        Jason Stewart  ...  Daniel Keim  Kenneth Utting  \
Jim Thomas                        1.0  ...     0.901668        0.688111   
Eleftherios Koutsofios            1.0  ...     0.884855        0.827867   
Lawrence A. Rowe                  1.0  ...     0.919080        0.927831   
Jonathan I. Helfman               1.0  ...     0.935770        0.474895   
Mary Brewster                     1.0  ...     0.824833        0.754505   

                        Ted Selker  Gabor T. Herman  Laxmi Parida  \
Jim Thomas                0.820618         0.764479      0.814604   
Eleftherios Koutsofios    0.798157         0.573037      0.827152   
Lawrence A. Rowe          0.753817         0.707075      0.947295   
Jonathan I. Helfman       0.582043         0.715821      0.923304   
Mary Brewster             0.744117         0.680156      0.900398   

                        Jeannine Pinto  Jonathan Furner  Clayton Lewis  \
Jim Thomas                    0.865160         0.852016       0.720174   
Eleftherios Koutsofios        1.000000         0.599181       0.565187   
Lawrence A. Rowe              1.000000         0.871963       0.779029   
Jonathan I. Helfman           1.000000         0.658411       0.935688   
Mary Brewster                 0.746454         0.661246       0.849666   

                        Francis P. Boscoe  Ian M. Soboroff  
Jim Thomas                       0.737125         0.941974  
Eleftherios Koutsofios           0.774721         0.741801  
Lawrence A. Rowe                 0.912814         0.927831  
Jonathan I. Helfman              0.774446         0.649930  
Mary Brewster                    0.516688         0.836337  

[5 rows x 150 columns]

In [47]:
#This is just the method online: https://gmarti.gitlab.io/ml/2017/09/07/how-to-sort-distance-matrix.html
#We have to clean data and modified the method

import numpy as np
from scipy.spatial.distance import pdist, squareform
from sklearn import datasets
from fastcluster import linkage

In [48]:
def seriation(Z,N,cur_index):
    '''
        input:
            - Z is a hierarchical tree (dendrogram)
            - N is the number of points given to the clustering process
            - cur_index is the position in the tree for the recursive traversal
        output:
            - order implied by the hierarchical tree Z
            
        seriation computes the order implied by a hierarchical tree (dendrogram)
    '''
    if cur_index < N:
        return [cur_index]
    else:
        left = int(Z[cur_index-N,0])
        right = int(Z[cur_index-N,1])
        return (seriation(Z,N,left) + seriation(Z,N,right))
    
def compute_serial_matrix(df,method="ward", dist_metric = "euclidean"):
    '''
        input:
            - dist_mat is a distance matrix
            - method = ["ward","single","average","complete"]
        output:
            - seriated_dist is the input dist_mat,
              but with re-ordered rows and columns
              according to the seriation, i.e. the
              order implied by the hierarchical tree
            - res_order is the order implied by
              the hierarhical tree
            - res_linkage is the hierarhical tree (dendrogram)
        
        compute_serial_matrix transforms a distance matrix into 
        a sorted distance matrix according to the order implied 
        by the hierarchical tree (dendrogram)
    '''
    dist_mat = squareform(pdist(df, metric=dist_metric))
    N = len(dist_mat)
    flat_dist_mat = squareform(dist_mat)
    res_linkage = linkage(flat_dist_mat, method=method,preserve_input=True)
    res_order = seriation(res_linkage, N, N + N-2)
    seriated_dist = np.zeros((N,N))
    a,b = np.triu_indices(N,k=1)
    seriated_dist[a,b] = dist_mat[ [res_order[i] for i in a], [res_order[j] for j in b]]
    seriated_dist[b,a] = seriated_dist[a,b]
    return seriated_dist, res_order, res_linkage

In [49]:
#ordered_dist_mat = {}
#ordered_dist_mat['ward'], res_order, res_linkage = compute_serial_matrix(dist_mat,"ward")
#ordered_dist_mat['single'], res_order, res_linkage = compute_serial_matrix(dist_mat,"single")
#ordered_dist_mat['average'], res_order, res_linkage = compute_serial_matrix(dist_mat,"average")
#ordered_dist_mat['complete'], res_order, res_linkage = compute_serial_matrix(dist_mat,"complete")
#ordered_dist_mat['centroid'], res_order, res_linkage = compute_serial_matrix(dist_mat,"centroid")
#ordered_dist_mat['weighted'], res_order, res_linkage = compute_serial_matrix(dist_mat,"weighted")
#ordered_dist_mat['median'], res_order, res_linkage = compute_serial_matrix(dist_mat,"median")
#solid = pd.DataFrame(ordered_dist_mat['ward'])
#solid.index = names
#solid.columns = names
#solid
df.values

array([[0.      , 0.902616, 0.87437 , ..., 0.720174, 0.737125, 0.941974],
       [0.902616, 0.      , 0.776393, ..., 0.565187, 0.774721, 0.741801],
       [0.87437 , 0.776393, 0.      , ..., 0.779029, 0.912814, 0.927831],
       ...,
       [0.720174, 0.565187, 0.779029, ..., 0.      , 0.876701, 0.897938],
       [0.737125, 0.774721, 0.912814, ..., 0.876701, 0.      , 0.832211],
       [0.941974, 0.741801, 0.927831, ..., 0.897938, 0.832211, 0.      ]])

In [50]:
#example

import numpy as np
a = np.array([[10, 20, 30, 40, 50],[ 6,  7,  8,  9, 10]])
your_permutation = [0,4,1,3,2]
#i = np.argsort(your_permutation)
a[:,your_permutation]

array([[10, 50, 20, 40, 30],
       [ 6, 10,  7,  9,  8]])

In [51]:
#ordered_dist_mat, res_order, res_linkage = compute_serial_matrix(df,"ward", "euclidean")
#res_order
#reorder(df, res_order)

In [52]:
def reorder(df, order):
    a = df.values
    permutation = order
    return a[:,permutation]

In [53]:
ordered_dist_mat, res_order, res_linkage = compute_serial_matrix(df,"ward", "euclidean")
#res_order
test_matrix = reorder(df, res_order)
test_matrix

array([[0.675483, 0.786447, 0.714682, ..., 0.941974, 0.770033, 0.868181],
       [0.840456, 0.817134, 0.830722, ..., 0.741801, 0.710586, 0.677969],
       [0.968255, 0.945237, 0.918889, ..., 0.927831, 0.72265 , 0.768545],
       ...,
       [0.870128, 0.89351 , 0.870954, ..., 0.897938, 0.767112, 0.754505],
       [0.879803, 0.95671 , 0.792564, ..., 0.832211, 0.75819 , 0.838563],
       [0.926689, 0.962059, 0.859512, ..., 0.      , 0.759808, 0.821826]])

In [54]:
def to_liquid(matrix):
    solid = pd.DataFrame(matrix)
    solid.index = names
    solid.columns = names
    solid.reset_index(inplace=True)
    liquid = solid.melt(id_vars='index', value_vars=list(df.columns[1:]), var_name="name2")
    liquid.columns = ['name1', 'name2', 'similarity']
    #print(liquid)
    return liquid
test_liquid = to_liquid(test_matrix)

In [55]:
pn.extension()

class Matrix_dropdown(param.Parameterized):
    reordering = param.ObjectSelector(default="ward",objects=["ward","single","average","complete", "centroid", "weighted", "median"])
    metric = param.ObjectSelector(default="euclidean", objects=["euclidean", "minkowski", "cityblock", "sqeuclidean", "cosine", "correlation", "hamming", "jaccard", "chebyshev", "canberra", "braycurtis"])
    def view(self):
        ordered_dist_mat, res_order, res_linkage = compute_serial_matrix(df,self.reordering, dist_metric = self.metric)
        reordered_matrix = reorder(df, res_order)
        #print(reordered_matrix)
        result = to_liquid(reordered_matrix)
        return result.hvplot.heatmap('name1', 'name2', 'similarity',
                      height=500, width=600, flip_yaxis=True, xaxis=None, yaxis=None, cmap=palette['kbc'])

matrix = Matrix_dropdown(name='Adjacency Matrix')
from bokeh.embed import components
pn.Column(matrix.param, matrix.view)

Column
    [0] Column(name='Param06540', width=300)
        [0] StaticText(value='<b>Adjacency Matrix</b>')
        [1] Select(name='Reordering', options=OrderedDict([('ward', ...]), value='ward')
        [2] Select(name='Metric', options=OrderedDict([('euclidean',...]), value='euclidean')
    [1] ParamMethod(method)